apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- api-deployment.yaml
- admin-deployment.yaml
- web-deployment.yaml

# Image transformer: maps short names to full GHCR paths
# CI workflows update these entries with @sha256:... digests after each build
images:
- digest: sha256:c96c1df5978d05ec3738716450b107ad16d53049c1ea208a70f20a54081f9922
  name: dhanam-admin
  newName: ghcr.io/madfam-org/dhanam/admin
- digest: sha256:dfe82899d58c01de76d70ac7fa01687eee3ad1fad128f3314a45a8d8f0861e6d
  name: dhanam-api
  newName: ghcr.io/madfam-org/dhanam/api
- digest: sha256:588a4f730be7533a373f10852a7df0b85a1611c6a950b5e6bd8305c68cfff2d0
  name: dhanam-web
  newName: ghcr.io/madfam-org/dhanam/web
